/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useLoader, useFrame } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function HomeScene(props) {
  const group = useRef();
  const { nodes, materials, animations } = useLoader(GLTFLoader, "/home.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <group name="Point001" position={[-3, 2.21, -3]} />
        <group name="pinkLight" position={[-0.03, 1.93, 0.2]} />
        <mesh
          material={materials["default"]}
          geometry={nodes.Cube005.geometry}
          name="Cube005"
          position={[-0.04, 2.47, -0.17]}
          scale={[0.44, 0.75, 0.34]}
        />
        <mesh
          material={materials["default"]}
          geometry={nodes.keyboard.geometry}
          name="keyboard"
          position={[-0.05, 1.72, 0.27]}
        >
          <mesh
            material={materials.buttons}
            geometry={nodes.keyBoard_button.geometry}
            name="keyBoard_button"
          />
        </mesh>
        <mesh
          material={materials["light glow"]}
          geometry={nodes.effect.geometry}
          name="effect"
          position={[-0.04, 2.87, -0.03]}
          scale={[1.44, 0.36, 1.44]}
        />
        <group name="computer" position={[-0.06, 1.72, -0.53]}>
          <mesh
            material={materials["default"]}
            geometry={nodes["Cube.004_0"].geometry}
            name="Cube.004_0"
          />
          <mesh
            material={materials.dark}
            geometry={nodes["Cube.004_1"].geometry}
            name="Cube.004_1"
          />
          <mesh
            material={materials["light glow"]}
            geometry={nodes["Cube.004_2"].geometry}
            name="Cube.004_2"
          />
        </group>
        <group name="mouse" position={[0.38, 1.72, 0.18]}>
          <mesh
            material={materials["default"]}
            geometry={nodes["Cube.007_0"].geometry}
            name="Cube.007_0"
          />
          <mesh
            material={materials.buttons}
            geometry={nodes["Cube.007_1"].geometry}
            name="Cube.007_1"
          />
        </group>
      </scene>
    </group>
  );
}
