/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/work.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <mesh
          material={materials.dark}
          geometry={nodes.buttonHolderRight.geometry}
          name="buttonHolderRight"
          position={[-0.01, -0.11, -0.01]}
          scale={[0.99, 0.99, 0.99]}
        />
        <mesh
          material={materials.dark}
          geometry={nodes.buttonHolderLeft.geometry}
          name="buttonHolderLeft"
          position={[-0.01, -0.11, -0.01]}
          scale={[0.99, 0.99, 0.99]}
        />
        <mesh
          material={materials['light glow pink']}
          geometry={nodes.buttomRight.geometry}
          name="buttomRight"
          position={[-0.01, -0.11, -0.01]}
          scale={[0.99, 0.99, 0.99]}
        />
        <mesh
          material={materials['light glow pink']}
          geometry={nodes.buttonLeft.geometry}
          name="buttonLeft"
          position={[-0.01, -0.11, -0.01]}
          scale={[0.99, 0.99, 0.99]}
        />
      </scene>
    </group>
  )
}
