/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useLoader, useFrame } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { work } from "../../meshes/work.glb";

export default function WorkScene(props) {
  const group = useRef();
  const { nodes, materials, animations } = useLoader(GLTFLoader, work);

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <group name="Point001" position={[-3, 2.21, -3]} />
        <mesh
          material={materials["default"]}
          geometry={nodes.Cube005.geometry}
          name="Cube005"
          position={[-0.04, 2.47, -0.17]}
          scale={[0.44, 0.75, 0.34]}
        />
        <mesh
          material={materials["light glow"]}
          geometry={nodes.effect.geometry}
          name="effect"
          position={[-0.04, 2.87, -0.03]}
          scale={[1.44, 0.36, 1.44]}
        />
        <mesh
          material={materials.dark}
          geometry={nodes.buttonHolderRight.geometry}
          name="buttonHolderRight"
          position={[-0.01, -0.11, -0.01]}
          scale={[0.99, 0.99, 0.99]}
        />
        <mesh
          material={materials.dark}
          geometry={nodes.buttonHolderLeft.geometry}
          name="buttonHolderLeft"
          position={[-0.01, -0.11, -0.01]}
          scale={[0.99, 0.99, 0.99]}
        />
        <mesh
          material={materials["light glow pink"]}
          geometry={nodes.buttomRight.geometry}
          name="buttomRight"
          position={[-0.01, -0.11, -0.01]}
          scale={[0.99, 0.99, 0.99]}
        />
        <mesh
          material={materials["light glow pink"]}
          geometry={nodes.buttonLeft.geometry}
          name="buttonLeft"
          position={[-0.01, -0.11, -0.01]}
          scale={[0.99, 0.99, 0.99]}
        />
      </scene>
    </group>
  );
}
